### ISSUE TITLE
White screen on authorising trakt

### ISSUE THREAD

**Issue by northernpowerhouse** [dexter21767/Trakt#9]
I've added the addon, and either on android or chromeos, when i click 'log in to trakt.tv', it authorises trakt and then takes me to a white page. On that page i get the following in the console:

```
Unchecked runtime.lastError: The message port closed before a response was received.
index.89c5ef8c.js:29 state.lists_personal Proxy
index.89c5ef8c.js:4 TypeError: Cannot read properties of null (reading 'slice')
    at index.89c5ef8c.js:29:42249
    at Ra (index.89c5ef8c.js:4:19864)
    at Proxy.<anonymous> (index.89c5ef8c.js:29:41817)
    at wl (index.89c5ef8c.js:4:4294)
    at cs.ge [as fn] (index.89c5ef8c.js:4:38569)
    at cs.run (index.89c5ef8c.js:1:5574)
    at N.update (index.89c5ef8c.js:4:39328)
    at Ar (index.89c5ef8c.js:4:664)
    at mh (index.89c5ef8c.js:4:2296)
```

**Comment by dexter21767** [comment]
the problem should be fixed now.
